### ISSUE TITLE
Support of extensions

### ISSUE THREAD

**Issue by f-bn** [f-bn/postgresql-server-role#22]
Find a way to install and enable PostgreSQL extensions on instances.

An idea on the fly for the DSL part :

```YAML
postgresql_extensions:
  - name: pg_cron # The name of the extension (the one used when doing CREATE EXTENSION command)
    databases: ['postgres'] # If needed, enable the extension for the defined database list
    cascade: true
    state: present  #Manage extension state inside the instance (=> CREATE EXTENSION)
```
